; ============================================================
;  Habit Tracker - ESP32-2432S032C (CYD 3.2" capacitivo)
;  Display ST7789 240x320 + Toque GT911 (I2C)
; ============================================================

[env:esp32-2432s032c]
platform      = espressif32@^6.9.0
board         = esp32dev
framework     = arduino

monitor_speed = 115200
upload_speed  = 460800       ; CH340 estavel nessa taxa

lib_deps =
    lovyan03/LovyanGFX@^1.1.16
    bblanchon/ArduinoJson@^7.2.1

build_flags =
    -DCORE_DEBUG_LEVEL=0
